### PR TITLE
Update receipt

### PR DESCRIPTION
**Pull request by hkalodner**
- Update ArbOS with https://github.com/OffchainLabs/arb-os/pull/228
- This adds a provenance field to transaction receipts

### CODE REVIEW

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- packages/arb-util/inbox/inboxMessage.go  2
- packages/arb-evm/evm/result.go  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6396286&bid=20741397)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- packages/arb-util/inbox/inboxMessage.go  2
- packages/arb-evm/evm/result.go  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6396286&bid=20741397)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- packages/arb-util/inbox/inboxMessage.go  2
- packages/arb-evm/evm/result.go  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6396286&bid=20741397)

**Review by edfelten — APPROVED** [review]
Looks good.

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- packages/arb-util/inbox/inboxMessage.go  2
- packages/arb-evm/evm/result.go  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6396286&bid=20741397)

**Review by edfelten — APPROVED** [review]
Approving. These changes just merge changes to derived files.

**Pull request merged**
