### PR TITLE
Fix missing logo file

### PR DESCRIPTION
**Pull request by adlerjohn**
Fix broken link to Offchain Labs logo file in readme.

### CODE REVIEW

**Comment by DZGoldman** [comment]
I, for one, do not trust this man.

**Comment by adlerjohn** [comment]
> I, for one, do not trust this man.

Same, tbh

**Review by DZGoldman — APPROVED** [review]

**Comment by DZGoldman** [comment]
LGTM

**Review by hkalodner — APPROVED** [review]
LGTM, thanks 😁

**Pull request merged**
