### PR TITLE
Update address table getter & typechain interfaces 

### PR DESCRIPTION
**Pull request by DZGoldman**
(Sidenote: We should probably have update-abi be an automated check before merging a PR, or even a pre-commit hook. )

### CODE REVIEW

**Comment by DZGoldman** [comment]
oo i should probably bump the arb-provider-ethers version too eh

**Review by hkalodner — APPROVED** [review]
LGTM pending CI

**Review by hkalodner — APPROVED** [review]
LGTM

**Review by hkalodner — APPROVED** [review]
LGTM

**Pull request merged**
