### PR TITLE
adding custom bridge to the docs

### PR DESCRIPTION
**Pull request by mahsamoosavi**

### CODE REVIEW

**Review by DZGoldman — COMMENTED** [review]
👍  - left a review on https://github.com/OffchainLabs/arbitrum-tutorials/pull/31#pullrequestreview-807464424

**Review by DZGoldman — APPROVED** [review]
lgtm

**Comment by DZGoldman** [comment]
some extra stuff seems have snuck into the diff somehow - approved / good to merge once that's sorted out @mahsamoosavi 👍

**Comment by joshuacolvin0** [comment]
docs moved to Nitro repo

**Pull request closed without merging**
