### PR TITLE
Clean up batcher

### PR DESCRIPTION
**Pull request by hkalodner**
- Split up stateless and stateful batcher functionality
- Add testing for stateless batcher

### CODE REVIEW

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 11
- Added 41
           

Complexity increasing per file
==============================
- packages/arb-tx-aggregator/batcher/statefulBatch.go  7
- packages/arb-evm/message/l2Message_test.go  1
- packages/arb-tx-aggregator/batcher/batcher_test.go  16
- packages/arb-tx-aggregator/rpc/launch.go  1
- packages/arb-tx-aggregator/batcher/statelessBatch.go  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6406064&bid=20764128)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 11
- Added 41
           

Complexity increasing per file
==============================
- packages/arb-tx-aggregator/batcher/statelessBatch.go  2
- packages/arb-tx-aggregator/rpc/launch.go  1
- packages/arb-tx-aggregator/batcher/statefulBatch.go  7
- packages/arb-tx-aggregator/batcher/batcher_test.go  16
- packages/arb-evm/message/l2Message_test.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6406064&bid=20764128)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 11
- Added 41
           

Complexity increasing per file
==============================
- packages/arb-evm/message/l2Message_test.go  1
- packages/arb-tx-aggregator/rpc/launch.go  1
- packages/arb-tx-aggregator/batcher/statelessBatch.go  2
- packages/arb-tx-aggregator/batcher/statefulBatch.go  7
- packages/arb-tx-aggregator/batcher/batcher_test.go  16
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6406064&bid=20764128)

**Review by joshuacolvin0 — APPROVED** [review]
LGTM, just a couple minor comments

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 11
- Added 41
           

Complexity increasing per file
==============================
- packages/arb-tx-aggregator/batcher/statelessBatch.go  2
- packages/arb-tx-aggregator/batcher/statefulBatch.go  7
- packages/arb-tx-aggregator/batcher/batcher_test.go  16
- packages/arb-evm/message/l2Message_test.go  1
- packages/arb-tx-aggregator/rpc/launch.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6406064&bid=20764128)

**Review by joshuacolvin0 — APPROVED** [review]

**Pull request merged**
