### PR TITLE
Next Arbitrum Release

### PR DESCRIPTION
**Pull request by hkalodner**
- Add support for all precompiles except RIPEMD160 and MODPOW
- Add (incomplete) support for ethereum websocket interface
- Add support for more compressed transaction type
- Add support for Kovan testnet to the aggregator and validator

### CODE REVIEW

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 70
- Added 142
           

Complexity increasing per file
==============================
- packages/arb-evm/message/l2Message.go  1
- packages/arb-tx-aggregator/arbostest/precompiles_test.go  8
- packages/arb-tx-aggregator/arbostestcontracts/receiver.go  3
- packages/arb-tx-aggregator/arbostestcontracts/create2.go  7
- packages/arb-evm/message/data.go  3
- packages/arb-tx-aggregator/rpc/launch.go  1
- packages/arb-tx-aggregator/arbostest/create2_test.go  4
- packages/arb-tx-aggregator/arbostest/evmOps_test.go  6
- packages/arb-validator-core/ethbridgetestcontracts/precompilestester.go  3
- packages/arb-tx-aggregator/arbostestcontracts/opcodes.go  3
- packages/arb-evm/message/data_test.go  2
         

Complexity decreasing per file
==============================
+ packages/arb-tx-aggregator/web3/eth.go  -1
+ packages/arb-tx-aggregator/machineobserver/observermanager.go  -12
         

Clones added
============
- packages/arb-tx-aggregator/arbostest/precompiles_test.go  4
- packages/arb-tx-aggregator/arbostestcontracts/receiver.go  5
- packages/arb-tx-aggregator/arbostestcontracts/create2.go  8
- packages/arb-avm-cpp/avm/src/machinestate/machineoperation.cpp  2
- packages/arb-tx-aggregator/arbostest/arbos_test.go  1
- packages/arb-avm-cpp/tests/opcodes.cpp  2
- packages/arb-avm-cpp/tests/ecops.cpp  2
- packages/arb-tx-aggregator/arbostest/evmOps_test.go  2
- packages/arb-validator-core/ethbridgetestcontracts/precompilestester.go  6
- packages/arb-avm-cpp/data_storage/src/value/value.cpp  4
- packages/arb-avm-cpp/tests/datastack.cpp  2
- packages/arb-tx-aggregator/arbostest/l2_test.go  24
- packages/arb-tx-aggregator/arbostestcontracts/opcodes.go  4
         

Clones removed
==============
+ packages/arb-tx-aggregator/web3/eth.go  -2
+ packages/arb-tx-aggregator/arbostest/create2_test.go  -3
+ packages/arb-tx-aggregator/arbostest/storage_test.go  -1
+ packages/arb-tx-aggregator/machineobserver/observermanager.go  -1
+ packages/arb-avm-cpp/tests/checkpoint.cpp  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6325752&bid=20557943)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 70
- Added 142
           

Complexity increasing per file
==============================
- packages/arb-tx-aggregator/arbostest/create2_test.go  4
- packages/arb-validator-core/ethbridgetestcontracts/precompilestester.go  3
- packages/arb-tx-aggregator/arbostestcontracts/create2.go  7
- packages/arb-evm/message/data_test.go  2
- packages/arb-tx-aggregator/arbostestcontracts/receiver.go  3
- packages/arb-bridge-eth/deploy/GlobalInbox.ts  4
- packages/arb-bridge-eth/deploy/ArbFactory.ts  4
- packages/arb-evm/message/data.go  3
- packages/arb-bridge-eth/deploy/InboxTopChallenge.ts  4
- packages/arb-evm/message/l2Message.go  1
- packages/arb-bridge-eth/deploy/ChallengeFactory.ts  4
- packages/arb-tx-aggregator/arbostestcontracts/opcodes.go  3
- packages/arb-bridge-eth/deploy/ExecutionChallenge.ts  4
- packages/arb-tx-aggregator/rpc/launch.go  1
- packages/arb-tx-aggregator/arbostest/evmOps_test.go  6
- packages/arb-bridge-eth/deploy/ArbRollup.ts  4
- packages/arb-bridge-eth/deploy/OneStepProof.ts  4
- packages/arb-tx-aggregator/arbostest/precompiles_test.go  8
         

Complexity decreasing per file
==============================
+ packages/arb-tx-aggregator/machineobserver/observermanager.go  -12
+ packages/arb-tx-aggregator/web3/eth.go  -1
         

Clones added
============
- packages/arb-validator-core/ethbridgetestcontracts/precompilestester.go  6
- packages/arb-tx-aggregator/arbostestcontracts/create2.go  8
- packages/arb-avm-cpp/tests/opcodes.cpp  2
- packages/arb-avm-cpp/avm/src/machinestate/machineoperation.cpp  2
- packages/arb-tx-aggregator/arbostestcontracts/receiver.go  5
- packages/arb-avm-cpp/data_storage/src/value/value.cpp  4
- packages/arb-avm-cpp/tests/datastack.cpp  2
- packages/arb-tx-aggregator/arbostestcontracts/opcodes.go  4
- packages/arb-avm-cpp/tests/ecops.cpp  2
- packages/arb-tx-aggregator/arbostest/l2_test.go  24
- packages/arb-tx-aggregator/arbostest/evmOps_test.go  2
- packages/arb-tx-aggregator/arbostest/arbos_test.go  1
- packages/arb-tx-aggregator/arbostest/precompiles_test.go  4
         

Clones removed
==============
+ packages/arb-tx-aggregator/arbostest/create2_test.go  -3
+ packages/arb-tx-aggregator/machineobserver/observermanager.go  -1
+ packages/arb-tx-aggregator/web3/eth.go  -2
+ packages/arb-tx-aggregator/arbostest/storage_test.go  -1
+ packages/arb-avm-cpp/tests/checkpoint.cpp  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6325752&bid=20557943)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 74
- Added 149
           

Complexity increasing per file
==============================
- packages/arb-tx-aggregator/rpc/launch.go  1
- packages/arb-tx-aggregator/arbostest/create2_test.go  4
- packages/arb-bridge-eth/deploy/OneStepProof.ts  4
- packages/arb-bridge-eth/deploy/ArbRollup.ts  4
- packages/arb-tx-aggregator/arbostestcontracts/create2.go  7
- packages/arb-tx-aggregator/arbostestcontracts/opcodes.go  3
- packages/arb-bridge-eth/deploy/ExecutionChallenge.ts  4
- packages/arb-evm/message/data_test.go  2
- packages/arb-evm/message/l2Message.go  1
- packages/arb-bridge-eth/deploy/ChallengeFactory.ts  4
- packages/arb-tx-aggregator/arbostestcontracts/receiver.go  3
- packages/arb-bridge-eth/deploy/InboxTopChallenge.ts  4
- packages/arb-validator-core/ethbridgetestcontracts/precompilestester.go  3
- packages/arb-tx-aggregator/arbostest/evmOps_test.go  6
- packages/arb-evm/message/data.go  3
- packages/arb-bridge-eth/deploy/ArbFactory.ts  4
- packages/arb-tx-aggregator/aggregator/aggregator.go  1
- packages/arb-bridge-eth/deploy/GlobalInbox.ts  4
- packages/arb-tx-aggregator/arbostest/precompiles_test.go  8
         

Complexity decreasing per file
==============================
+ packages/arb-tx-aggregator/machineobserver/observermanager.go  -12
+ packages/arb-tx-aggregator/web3/eth.go  -1
         

Clones added
============
- packages/arb-avm-cpp/tests/datastack.cpp  2
- packages/arb-avm-cpp/tests/ecops.cpp  2
- packages/arb-tx-aggregator/arbostest/arbos_test.go  1
- packages/arb-tx-aggregator/arbostestcontracts/create2.go  8
- packages/arb-tx-aggregator/arbostestcontracts/opcodes.go  4
- packages/arb-avm-cpp/avm/src/machinestate/machineoperation.cpp  2
- packages/arb-tx-aggregator/arbostest/l2_test.go  24
- packages/arb-tx-aggregator/arbostestcontracts/receiver.go  5
- packages/arb-avm-cpp/tests/opcodes.cpp  2
- packages/arb-validator-core/ethbridgetestcontracts/precompilestester.go  6
- packages/arb-tx-aggregator/arbostest/evmOps_test.go  2
- packages/arb-avm-cpp/data_storage/src/value/value.cpp  4
- packages/arb-tx-aggregator/arbostest/precompiles_test.go  4
         

Clones removed
==============
+ packages/arb-tx-aggregator/arbostest/create2_test.go  -3
+ packages/arb-tx-aggregator/machineobserver/observermanager.go  -1
+ packages/arb-avm-cpp/tests/checkpoint.cpp  -3
+ packages/arb-tx-aggregator/arbostest/storage_test.go  -1
+ packages/arb-tx-aggregator/web3/eth.go  -2
+ packages/arb-validator/rollupmanager/manager.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6325752&bid=20557943)

**Review by edfelten — APPROVED** [review]
Approving this, because it is only merging already-reviewed changes from the develop branch.

**Pull request merged**
