### PR TITLE
Fix grammatical error on the website

### PR DESCRIPTION
**Pull request by keyboard-clacker**
There was a verb missing in this sentence, I assumed it was meant to be `be`

### CODE REVIEW

**Comment by keyboard-clacker** [comment]
I'm pretty sure I filled out and signed the agreement, but looks like it didn't take. Any ideas?

**Review by hkalodner — APPROVED** [review]
Sorry about the delay adding you to the CLA list and thanks for the contribution!

**Comment by keyboard-clacker** [comment]
Oh great thanks @hkalodner ! I thought it may have been something on my end, fantastic

**Comment by keyboard-clacker** [comment]
Oh great thanks @hkalodner ! I thought it may have been something on my end, fantastic

**Pull request merged**
