### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by hkalodner**
- Bump version to v0.7.2
- Update some `buidler` related JS packages

### CODE REVIEW

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- packages/arb-bridge-eth/deploy/ArbRollup.ts  4
- packages/arb-bridge-eth/deploy/GlobalInbox.ts  4
- packages/arb-bridge-eth/deploy/ExecutionChallenge.ts  4
- packages/arb-bridge-eth/deploy/OneStepProof.ts  4
- packages/arb-bridge-eth/deploy/ArbFactory.ts  4
- packages/arb-bridge-eth/deploy/InboxTopChallenge.ts  4
- packages/arb-bridge-eth/deploy/ChallengeFactory.ts  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6325923&bid=20558417)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- packages/arb-bridge-eth/deploy/ExecutionChallenge.ts  4
- packages/arb-bridge-eth/deploy/OneStepProof.ts  4
- packages/arb-bridge-eth/deploy/ArbFactory.ts  4
- packages/arb-bridge-eth/deploy/InboxTopChallenge.ts  4
- packages/arb-bridge-eth/deploy/ChallengeFactory.ts  4
- packages/arb-bridge-eth/deploy/GlobalInbox.ts  4
- packages/arb-bridge-eth/deploy/ArbRollup.ts  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6325923&bid=20558417)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- packages/arb-bridge-eth/deploy/GlobalInbox.ts  4
- packages/arb-bridge-eth/deploy/OneStepProof.ts  4
- packages/arb-bridge-eth/deploy/ExecutionChallenge.ts  4
- packages/arb-bridge-eth/deploy/ChallengeFactory.ts  4
- packages/arb-bridge-eth/deploy/ArbFactory.ts  4
- packages/arb-bridge-eth/deploy/ArbRollup.ts  4
- packages/arb-bridge-eth/deploy/InboxTopChallenge.ts  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6325923&bid=20558417)

**Review by edfelten — APPROVED** [review]
Looks good.

**Pull request merged**
