### PR TITLE
move goerli testnet rollup addresses to useful addresses page

### PR DESCRIPTION
**Pull request by DZGoldman**

### CODE REVIEW

**Review by gzeoneth — COMMENTED** [review]
Not a big fan of having 3 columns of addresses

**Comment by fredlacs** [comment]
> Not a big fan of having 3 columns of addresses

temporary tho, soon no more rinkeby

**Comment by gzeoneth** [comment]
> > Not a big fan of having 3 columns of addresses
> 
> temporary tho, soon no more rinkeby

why don't move when it's soon haha, its really ugly on the page

**Comment by DZGoldman** [comment]
@gzeoneth 
> Not a big fan of having 3 columns of addresses

Oh, well my plan was to a 4th next lol (Nova). It's a pretty niche / for-devs thing, so I kinda like having them all in one place (as is why have 2 in useful addresses and one elsewhere, which is confusing.). Maybe we can play with CSS-ing the table better?

**Comment by gzeoneth** [comment]
> @gzeoneth wa u think https://deploy-preview-51--hopeful-rosalind-235059.netlify.app/docs/useful_addresses

oh looks good

**Review by gzeoneth — DISMISSED** [review]

**Review by gzeoneth — APPROVED** [review]
fixed a minor thing, LGTM

**Pull request merged**
