### PR TITLE
Checkpoint restore benchmark on value cache branch

### PR DESCRIPTION
**Pull request by joshuacolvin0**
Benchmark the amount of time it takes to restore a chain of 10,000 tuples.

### CODE REVIEW

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 66
- Added 97
           

Complexity increasing per file
==============================
- packages/arb-validator-core/ethbridgetestcontracts/precompilestester.go  3
- packages/arb-tx-aggregator/rpc/launch.go  1
- packages/arb-tx-aggregator/arbostest/evmOps_test.go  6
- packages/arb-tx-aggregator/arbostest/precompiles_test.go  8
- packages/arb-tx-aggregator/arbostestcontracts/receiver.go  3
- packages/arb-tx-aggregator/arbostestcontracts/opcodes.go  3
         

Complexity decreasing per file
==============================
+ packages/arb-tx-aggregator/machineobserver/observermanager.go  -12
+ packages/arb-tx-aggregator/web3/eth.go  -1
         

Clones added
============
- packages/arb-validator-core/ethbridgetestcontracts/precompilestester.go  6
- packages/arb-avm-cpp/tests/opcodes.cpp  2
- packages/arb-tx-aggregator/arbostest/arbos_test.go  1
- packages/arb-tx-aggregator/arbostest/evmOps_test.go  2
- packages/arb-tx-aggregator/arbostest/precompiles_test.go  4
- packages/arb-avm-cpp/tests/ecops.cpp  2
- packages/arb-avm-cpp/tests/machine.cpp  2
- packages/arb-tx-aggregator/arbostest/l2_test.go  14
- packages/arb-avm-cpp/data_storage/src/value/value.cpp  4
- packages/arb-avm-cpp/avm/src/machinestate/machineoperation.cpp  2
- packages/arb-tx-aggregator/arbostestcontracts/receiver.go  5
- packages/arb-avm-cpp/tests/datastack.cpp  2
- packages/arb-tx-aggregator/arbostestcontracts/opcodes.go  4
         

Clones removed
==============
+ packages/arb-tx-aggregator/machineobserver/observermanager.go  -1
+ packages/arb-avm-cpp/tests/checkpoint.cpp  -3
+ packages/arb-tx-aggregator/web3/eth.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6304356&bid=20501205)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           

Clones added
============
- packages/arb-avm-cpp/tests/datastack.cpp  2
- packages/arb-avm-cpp/data_storage/src/value/value.cpp  4
         

Clones removed
==============
+ packages/arb-avm-cpp/tests/checkpoint.cpp  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6304356&bid=20501205)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 1
           

Clones added
============
- packages/arb-avm-cpp/data_storage/src/value/value.cpp  4
- packages/arb-avm-cpp/tests/datastack.cpp  2
         

Clones removed
==============
+ packages/arb-avm-cpp/tests/checkpoint.cpp  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6304356&bid=20501205)

**Comment by joshuacolvin0** [comment]
Included benchmark in with #585

**Pull request closed without merging**
