### PR TITLE
Save database checkpoint on SIGUSR1

### PR DESCRIPTION
**Pull request by joshuacolvin0**
Check if directory exists every time.  Cannot check on startup because SIGUSR1 may never be used to trigger database checkpoint save.

### CODE REVIEW

**Comment by PlasmaPower** [comment]
Hmm.. we should consider doing this from the Go side so the signal doesn't need targeted at the core thread. This works too, but I believe it requires you target the SIGUSR1 at the core thread (I could be wrong).

**Comment by joshuacolvin0** [comment]
> Hmm.. we should consider doing this from the Go side so the signal doesn't need targeted at the core thread. This works too, but I believe it requires you target the SIGUSR1 at the core thread (I could be wrong).

Worked really well during testing, just had to run `ps` to get PID and send SIGUSR1 to it.

**Comment by PlasmaPower** [comment]
I might be wrong then. If that worked during testing this sounds good to me.

**Review by PlasmaPower — APPROVED** [review]
LGTM

**Pull request merged**
