### PR TITLE
Pre 155

### PR DESCRIPTION
**Pull request by hkalodner**
Note: This PR will break aggregator compatibility with the current ArbOS version in master

- Update ArbOS with https://github.com/OffchainLabs/arb-os/pull/221
- Add support for ArbOS update to aggregator

### CODE REVIEW

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Clones added
============
- packages/arb-tx-aggregator/arbostest/l2_test.go  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6373518&bid=20680076)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 5
           

Clones added
============
- packages/arb-tx-aggregator/arbostest/l2_test.go  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6373518&bid=20680076)

**Review by edfelten — APPROVED** [review]
Looks good.

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 5
           

Clones added
============
- packages/arb-tx-aggregator/arbostest/l2_test.go  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6373518&bid=20680076)

**Review by edfelten — APPROVED** [review]
Looks good.

**Pull request merged**
