### PR TITLE
Deduplicate Values when deserializing Machine type

### PR DESCRIPTION
**Pull request by joshuacolvin0**
Currently a work in progress, working on fixing object lifetimes.

### CODE REVIEW

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           

Clones added
============
- packages/arb-avm-cpp/data_storage/src/value/value.cpp  2
         

Clones removed
==============
+ packages/arb-avm-cpp/tests/checkpoint.cpp  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6277126&bid=20431043)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           

Clones added
============
- packages/arb-avm-cpp/data_storage/src/value/value.cpp  2
         

Clones removed
==============
+ packages/arb-avm-cpp/tests/checkpoint.cpp  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6277126&bid=20431043)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           

Clones added
============
- packages/arb-avm-cpp/data_storage/src/value/value.cpp  2
         

Clones removed
==============
+ packages/arb-avm-cpp/tests/checkpoint.cpp  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6277126&bid=20431043)

**Comment by joshuacolvin0** [comment]
Tuples and individual values with more than 1 reference are added to a cache when loading machine from database.

Depending on further testing, may want to only add tuples to cache.

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           

Clones added
============
- packages/arb-avm-cpp/data_storage/src/value/value.cpp  2
         

Clones removed
==============
+ packages/arb-avm-cpp/tests/checkpoint.cpp  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6277126&bid=20431043)

**Comment by joshuacolvin0** [comment]
Closing this PR because #585 will be used instead.

**Pull request closed without merging**
