### PR TITLE
Security fixes

### PR DESCRIPTION
**Pull request by hkalodner**
- Check to make sure that ERC-20 deposits and withdrawals are successful
- Automically protect the master copies of the rollup contract and challenge contracts
- Throw `stack_too_small` exceptions any time the stack or auxstack underflows
- Add tests to verify all of these fixes

### CODE REVIEW

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones added
============
- packages/arb-validator-core/ethbridgecontracts/onestepproof.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=5870192&bid=19214517)

**Review by edfelten — DISMISSED** [review]
Looks good.

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones added
============
- packages/arb-validator-core/ethbridgecontracts/onestepproof.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=5870192&bid=19214517)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- packages/arb-validator-core/ethbridgecontracts/onestepproof.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=5870192&bid=19214517)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- packages/arb-validator-core/ethbridgecontracts/onestepproof.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=5870192&bid=19214517)

**Pull request merged**
