### PR TITLE
update launch-geth args to fix cmd run failure

### PR DESCRIPTION
**Pull request by Dhanush123**
Before this fix, when I ran `yarn docker:geth` as specified in https://developer.offchainlabs.com/docs/local_blockchain, the command failed with the following stacktrace:

`yarn run v1.13.0
$ yarn workspace arb-bridge-eth docker:geth
$ rm -rf deployments/parity && ./scripts/launch-geth
c54c860a7bf65464ea33cf03a5ef01b49722ad52fa0a152d2b9ce57dce97102f
Connection to localhost port 7545 [tcp/nta-us] succeeded!
Finished waiting for geth on localhost:7545...
$ /Users/dhanush/Documents/GitHub/arbitrum/packages/arb-bridge-eth/node_modules/.bin/buidler deploy --network parity --export bridge_eth_addresses.json
Prepending SPDX License Identifier to 0 sources: Apache-2.0
All contracts have already been compiled, skipping compilation.
failed to get chainId, falling back on net_version...
Error BDLR109: Cannot connect to the network parity.
Please make sure your node is running, and check your internet connection and networks config

For more info go to https://buidler.dev/BDLR109 or run Buidler with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: No such container: arb-bridge-eth-geth
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/dhanush/.nvm/versions/node/v10.15.1/bin/node
Arguments: /Users/dhanush/.nvm/versions/node/v10.15.1/lib/node_modules/yarn/lib/cli.js docker:geth
Directory: /Users/dhanush/Documents/GitHub/arbitrum/packages/arb-bridge-eth
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

### CODE REVIEW

**Review by allenyin55 — APPROVED** [review]
LGTM

**Comment by allanjwarner** [comment]
Hi @Dhanush123 thanks so much for opening this! In order for us to merge, we need a CLA signed (attached), Would you mind signing the attached and sending it back? Much appreciated again! 
[Arbitrum contributor agreement -- individual.pdf](https://github.com/OffchainLabs/arbitrum/files/6351373/Arbitrum.contributor.agreement.--.individual.pdf)

**Comment by ggwpez** [comment]
This is already fixed in 9abb8295df964be9532b53ec033c716722508025 but since the tutorial uses `v0.7.3`, it is not working there.

**Comment by Dhanush123** [comment]
> This is already fixed in [9abb829](https://github.com/OffchainLabs/arbitrum/commit/9abb8295df964be9532b53ec033c716722508025) but since the tutorial uses `v0.7.3`, it is not working there.
> @allanjwarner
> 
> PS: The tutorial was changed to use `v0.8.0` now where it is already fixed.

Since the tutorial is now using an updated, fixed version, is this PR still necessary (I can submit the CLA) or should it be closed?

**Pull request closed without merging**
