### PR TITLE
Fix eth_getStorageAt

### PR DESCRIPTION
**Pull request by hkalodner**

### CODE REVIEW

**Review by PlasmaPower — APPROVED** [review]
LGTM

**Comment by PlasmaPower** [comment]
There's also a hexutil.Int right? I'm not sure of the comparative advantages/disadvantages, but would it support `0x0` where Bytes may not?

**Review by joshuacolvin0 — APPROVED** [review]
LGTM

**Comment by hkalodner** [comment]
The bug was that we were using `hexutil.Big` which is the int version, but that rejects data with leading 0s as invalid which standard tooling expects to work. This shifts us over to accepting arbitrary hex input which is what we want

**Pull request merged**
