### PR TITLE
Add support for EC precompiles

### PR DESCRIPTION
**Pull request by hkalodner**
- Update arbos with https://github.com/OffchainLabs/arb-os/pull/211
- Add tests for new precompiles

### CODE REVIEW

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 29
           

Complexity increasing per file
==============================
- packages/arb-tx-aggregator/arbostest/precompiles_test.go  8
         

Clones added
============
- packages/arb-tx-aggregator/arbostest/precompiles_test.go  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6225531&bid=20289694)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 29
           

Complexity increasing per file
==============================
- packages/arb-tx-aggregator/arbostest/precompiles_test.go  8
         

Clones added
============
- packages/arb-tx-aggregator/arbostest/precompiles_test.go  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6225531&bid=20289694)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 29
           

Complexity increasing per file
==============================
- packages/arb-tx-aggregator/arbostest/precompiles_test.go  8
         

Clones added
============
- packages/arb-tx-aggregator/arbostest/precompiles_test.go  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6225531&bid=20289694)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 29
           

Complexity increasing per file
==============================
- packages/arb-tx-aggregator/arbostest/precompiles_test.go  8
         

Clones added
============
- packages/arb-tx-aggregator/arbostest/precompiles_test.go  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6225531&bid=20289694)

**Review by edfelten — APPROVED** [review]
Looks good.

**Pull request merged**
