### PR TITLE
Withdraw event

### PR DESCRIPTION
**Pull request by hkalodner**
- Update ArbOS with https://github.com/OffchainLabs/arb-os/pull/229
- Update go-ethereum version
- Update contract go ABIs with new version

### CODE REVIEW

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 21
- Added 48
           

Complexity increasing per file
==============================
- packages/arb-evm/arboscontracts/arbsys.go  11
- packages/arb-evm/arboscontracts/arbERC20.go  12
- packages/arb-tx-aggregator/arbostest/withdraw_test.go  12
- packages/arb-tx-aggregator/arbostestcontracts/fibonacci.go  10
         

Complexity decreasing per file
==============================
+ packages/arb-tx-aggregator/arbostest/buddy_test.go  -2
         

Clones added
============
- packages/arb-evm/arboscontracts/arbsys.go  43
- packages/arb-evm/arboscontracts/arbERC20.go  170
- packages/arb-validator-core/ethbridgetestcontracts/machinetester.go  1
- packages/arb-validator-core/ethbridgetestcontracts/precompilestester.go  1
- packages/arb-tx-aggregator/arbostestcontracts/receiver.go  5
- packages/arb-validator-core/ethbridgetestcontracts/rolluptester.go  14
- packages/arb-tx-aggregator/arbostest/withdraw_test.go  13
- packages/arb-tx-aggregator/arbostestcontracts/fibonacci.go  13
- packages/arb-validator-core/ethbridgecontracts/challengefactory.go  5
- packages/arb-validator-core/ethbridgecontracts/arbfactory.go  3
- packages/arb-tx-aggregator/arbostest/calls_test.go  6
- packages/arb-validator-core/ethbridgecontracts/executionchallenge.go  2
- packages/arb-validator-core/ethbridgetestcontracts/valuetester.go  5
- packages/arb-validator-core/ethbridgecontracts/inboxtopchallenge.go  6
- packages/arb-validator-core/ethbridgecontracts/onestepproof.go  2
- packages/arb-evm/arboscontracts/arbinfo.go  2
- packages/arb-tx-aggregator/arbostestcontracts/storage.go  2
- packages/arb-validator-core/ethbridgetestcontracts/messagetester.go  5
         

Clones removed
==============
+ packages/arb-tx-aggregator/arbostest/buddy_test.go  -4
+ packages/arb-tx-aggregator/arbostest/arbsys_test.go  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6397539&bid=20743909)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 23
- Added 50
           

Complexity increasing per file
==============================
- packages/arb-evm/arboscontracts/arbERC20.go  12
- packages/arb-tx-aggregator/arbostest/withdraw_test.go  12
- packages/arb-tx-aggregator/arbostestcontracts/fibonacci.go  10
- packages/arb-evm/arboscontracts/arbsys.go  11
         

Complexity decreasing per file
==============================
+ packages/arb-tx-aggregator/arbostest/buddy_test.go  -2
         

Clones added
============
- packages/arb-validator-core/ethbridgecontracts/onestepproof.go  1
- packages/arb-tx-aggregator/arbostestcontracts/receiver.go  4
- packages/arb-validator-core/ethbridgecontracts/challengefactory.go  4
- packages/arb-evm/arboscontracts/arbERC20.go  169
- packages/arb-tx-aggregator/arbostestcontracts/storage.go  1
- packages/arb-validator-core/ethbridgetestcontracts/messagetester.go  13
- packages/arb-tx-aggregator/arbostest/withdraw_test.go  13
- packages/arb-validator-core/ethbridgecontracts/arbfactory.go  2
- packages/arb-validator-core/ethbridgetestcontracts/rolluptester.go  13
- packages/arb-tx-aggregator/arbostest/calls_test.go  6
- packages/arb-validator-core/ethbridgetestcontracts/valuetester.go  4
- packages/arb-evm/arboscontracts/arbinfo.go  1
- packages/arb-validator-core/ethbridgecontracts/executionchallenge.go  1
- packages/arb-validator-core/ethbridgecontracts/inboxtopchallenge.go  5
- packages/arb-tx-aggregator/arbostestcontracts/fibonacci.go  12
- packages/arb-evm/arboscontracts/arbsys.go  42
         

Clones removed
==============
+ packages/arb-validator-core/ethbridgetestcontracts/challengetester.go  -1
+ packages/arb-tx-aggregator/arbostestcontracts/opcodes.go  -1
+ packages/arb-tx-aggregator/arbostestcontracts/create2.go  -1
+ packages/arb-tx-aggregator/arbostest/buddy_test.go  -4
+ packages/arb-tx-aggregator/arbostestcontracts/failedsend.go  -1
+ packages/arb-tx-aggregator/arbostestcontracts/simple.go  -1
+ packages/arb-evm/message/ethbridge_test.go  -2
+ packages/arb-tx-aggregator/arbostest/arbsys_test.go  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6397539&bid=20743909)

**Review by edfelten — APPROVED** [review]
Looks good.

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 23
- Added 50
           

Complexity increasing per file
==============================
- packages/arb-evm/arboscontracts/arbsys.go  11
- packages/arb-tx-aggregator/arbostest/withdraw_test.go  12
- packages/arb-evm/arboscontracts/arbERC20.go  12
- packages/arb-tx-aggregator/arbostestcontracts/fibonacci.go  10
         

Complexity decreasing per file
==============================
+ packages/arb-tx-aggregator/arbostest/buddy_test.go  -2
         

Clones added
============
- packages/arb-validator-core/ethbridgecontracts/challengefactory.go  4
- packages/arb-validator-core/ethbridgetestcontracts/valuetester.go  4
- packages/arb-evm/arboscontracts/arbsys.go  42
- packages/arb-validator-core/ethbridgetestcontracts/rolluptester.go  13
- packages/arb-tx-aggregator/arbostestcontracts/receiver.go  4
- packages/arb-tx-aggregator/arbostest/withdraw_test.go  13
- packages/arb-evm/arboscontracts/arbERC20.go  169
- packages/arb-evm/arboscontracts/arbinfo.go  1
- packages/arb-tx-aggregator/arbostest/calls_test.go  6
- packages/arb-validator-core/ethbridgecontracts/arbfactory.go  2
- packages/arb-validator-core/ethbridgecontracts/onestepproof.go  1
- packages/arb-tx-aggregator/arbostestcontracts/storage.go  1
- packages/arb-validator-core/ethbridgecontracts/inboxtopchallenge.go  5
- packages/arb-validator-core/ethbridgetestcontracts/messagetester.go  13
- packages/arb-validator-core/ethbridgecontracts/executionchallenge.go  1
- packages/arb-tx-aggregator/arbostestcontracts/fibonacci.go  12
         

Clones removed
==============
+ packages/arb-tx-aggregator/arbostest/buddy_test.go  -4
+ packages/arb-validator-core/ethbridgetestcontracts/challengetester.go  -1
+ packages/arb-tx-aggregator/arbostestcontracts/simple.go  -1
+ packages/arb-tx-aggregator/arbostestcontracts/create2.go  -1
+ packages/arb-tx-aggregator/arbostestcontracts/opcodes.go  -1
+ packages/arb-evm/message/ethbridge_test.go  -2
+ packages/arb-tx-aggregator/arbostest/arbsys_test.go  -5
+ packages/arb-tx-aggregator/arbostestcontracts/failedsend.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6397539&bid=20743909)

**Review by edfelten — APPROVED** [review]
Looks good.

**Pull request merged**
