### PR TITLE
use BigNumber for HashOnlyValue

### PR DESCRIPTION
**Pull request by julientregoat**

### CODE REVIEW

**Comment by hkalodner** [comment]
I'm guessing that this supersedes #238?

**Comment by hkalodner** [comment]
Actually it looks like this only includes the HashOnlyValue change and removing node-fetch from the yarn.lock, but not from package.json

**Comment by hkalodner** [comment]
#238 is now merged

**Comment by julientregoat** [comment]
should be gtg

**Comment by hkalodner** [comment]
Looks like one of the tests has to be upgraded to match the change

**Pull request merged**
