### PR TITLE
Update Call message

### PR DESCRIPTION
**Pull request by hkalodner**
- Add value field to call message
- Fixes mutations in call implementation
- Update ArbOS with https://github.com/OffchainLabs/arb-os/pull/210
- Add a bunch of tests to verify call semantics

### CODE REVIEW

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
- Added 13
           

Complexity increasing per file
==============================
- packages/arb-tx-aggregator/arbostestcontracts/receiver.go  3
         

Clones added
============
- packages/arb-tx-aggregator/arbostest/l2_test.go  14
- packages/arb-tx-aggregator/arbostestcontracts/receiver.go  5
         

Clones removed
==============
+ packages/arb-tx-aggregator/arbostest/arbos_test.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6263934&bid=20396739)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
- Added 13
           

Complexity increasing per file
==============================
- packages/arb-tx-aggregator/arbostestcontracts/receiver.go  3
         

Clones added
============
- packages/arb-tx-aggregator/arbostestcontracts/receiver.go  5
- packages/arb-tx-aggregator/arbostest/l2_test.go  14
         

Clones removed
==============
+ packages/arb-tx-aggregator/arbostest/arbos_test.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6263934&bid=20396739)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
- Added 13
           

Complexity increasing per file
==============================
- packages/arb-tx-aggregator/arbostestcontracts/receiver.go  3
         

Clones added
============
- packages/arb-tx-aggregator/arbostestcontracts/receiver.go  5
- packages/arb-tx-aggregator/arbostest/l2_test.go  14
         

Clones removed
==============
+ packages/arb-tx-aggregator/arbostest/arbos_test.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6263934&bid=20396739)

**Review by edfelten — APPROVED** [review]
Looks good.

**Pull request merged**
