### PR TITLE
Update Solidity_Support.md

### PR DESCRIPTION
**Pull request by gzeoneth**

### CODE REVIEW

**Comment by gzeoneth** [comment]
Might want to deprecate the MulticallV2 too.
https://github.com/OffchainLabs/arbitrum/blob/master/packages/arb-bridge-peripherals/contracts/rpc-utils/MulticallV2.sol

**Review by fredlacs — APPROVED** [review]
LGTM

**Comment by fredlacs** [comment]
> Might want to deprecate the MulticallV2 too. https://github.com/OffchainLabs/arbitrum/blob/master/packages/arb-bridge-peripherals/contracts/rpc-utils/MulticallV2.sol

why?

**Comment by gzeoneth** [comment]
> > Might want to deprecate the MulticallV2 too. https://github.com/OffchainLabs/arbitrum/blob/master/packages/arb-bridge-peripherals/contracts/rpc-utils/MulticallV2.sol
> 
> why?

https://github.com/OffchainLabs/arbitrum/blob/1e433873d236af66301bdea7b690a99d63efa6ab/packages/arb-bridge-peripherals/contracts/rpc-utils/MulticallV2.sol#L178
https://github.com/OffchainLabs/arbitrum/blob/1e433873d236af66301bdea7b690a99d63efa6ab/packages/arb-bridge-peripherals/contracts/rpc-utils/MulticallV2.sol#L206
these are wrong

**Pull request merged**
