### PR TITLE
Arbos testing

### PR DESCRIPTION
**Pull request by hkalodner**
- Add create2 test
- Add convenient deposit method to ethbridge buidler config
- Update ArbOS with https://github.com/OffchainLabs/arb-os/pull/203
- Update snapshot system to support a limited set of recent snapshots
- Change validator docker file to use Debian instead of alpine to fix crash and simplify build. This brings our validator docker build in line with our circleci docker build which should make maintenance easier

### CODE REVIEW

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 16
- Added 53
           

Complexity increasing per file
==============================
- packages/arb-tx-aggregator/arbostestcontracts/simple.go  3
- packages/arb-tx-aggregator/arbostestcontracts/create2.go  3
- packages/arb-tx-aggregator/txdb/snapshotCache.go  4
- packages/arb-tx-aggregator/arbostest/create2_test.go  28
         

Complexity decreasing per file
==============================
+ packages/arb-tx-aggregator/txdb/txdb.go  -3
         

Clones added
============
- packages/arb-tx-aggregator/arbostestcontracts/simple.go  4
- packages/arb-tx-aggregator/arbostestcontracts/create2.go  4
- packages/arb-tx-aggregator/web3/eth.go  2
- packages/arb-tx-aggregator/arbostest/create2_test.go  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6086312&bid=19925560)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 16
- Added 57
           

Complexity increasing per file
==============================
- packages/arb-tx-aggregator/arbostestcontracts/create2.go  3
- packages/arb-tx-aggregator/txdb/snapshotCache.go  4
- packages/arb-provider-go/validatorProxy.go  1
- packages/arb-tx-aggregator/arbostest/create2_test.go  28
- packages/arb-evm/evm/evm.pb.go  8
- packages/arb-tx-aggregator/arbostestcontracts/simple.go  3
         

Complexity decreasing per file
==============================
+ packages/arb-tx-aggregator/txdb/txdb.go  -3
         

Clones added
============
- packages/arb-tx-aggregator/arbostestcontracts/create2.go  4
- packages/arb-tx-aggregator/arbostest/create2_test.go  6
- packages/arb-evm/evm/evm.pb.go  2
- packages/arb-tx-aggregator/arbostestcontracts/simple.go  4
- packages/arb-tx-aggregator/web3/eth.go  2
         

Clones removed
==============
+ packages/arb-provider-go/validatorProxy.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6086312&bid=19925560)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 16
- Added 57
           

Complexity increasing per file
==============================
- packages/arb-tx-aggregator/txdb/snapshotCache.go  4
- packages/arb-evm/evm/evm.pb.go  8
- packages/arb-tx-aggregator/arbostest/create2_test.go  28
- packages/arb-provider-go/validatorProxy.go  1
- packages/arb-tx-aggregator/arbostestcontracts/simple.go  3
- packages/arb-tx-aggregator/arbostestcontracts/create2.go  3
         

Complexity decreasing per file
==============================
+ packages/arb-tx-aggregator/txdb/txdb.go  -3
         

Clones added
============
- packages/arb-evm/evm/evm.pb.go  2
- packages/arb-tx-aggregator/arbostest/create2_test.go  6
- packages/arb-tx-aggregator/web3/eth.go  2
- packages/arb-tx-aggregator/arbostestcontracts/simple.go  4
- packages/arb-tx-aggregator/arbostestcontracts/create2.go  4
         

Clones removed
==============
+ packages/arb-provider-go/validatorProxy.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6086312&bid=19925560)

**Review by behzad1191 — COMMENTED** [review]
arbi

**Pull request merged**
