### PR TITLE
Update liquidity exit documentation

### LINKED ISSUE #1931: Withdrawals Dev Docs Outdated
The [withdrawals page](https://developer.offchainlabs.com/docs/withdrawals) of the developer docs contains a reference to a `fastWithdrawalFromL2` function which was removed months ago in [this commit](https://github.com/OffchainLabs/arbitrum/commit/0af26fb2740282991e23006d3ff612ee6f142c9e#diff-1c9e8f039dbc46a66402d57ca3df1d4b18ae692e4adea35bfc602f8eb0ac7648) in favor of `transferExitAndCall`. It looks like [this description](https://github.com/OffchainLabs/arbitrum/blob/89e1f6234fe133253f445db44ec1612d57389c45/docs/sol_contract_docs/md_docs/arb-bridge-peripherals/tokenbridge/ethereum/gateway/L1ArbitrumExtendedGateway.md) is more up-to-date for what "fast withdrawals" got refactored into, so maybe we could update the website to reflect that?

### PR DESCRIPTION
**Pull request by theoilie**
Fixes #1931 . See [here](https://github.com/OffchainLabs/arbitrum/blob/afa60b9ab2f8645fb292251d74f2adb42ecde047/packages/arb-bridge-peripherals/contracts/tokenbridge/ethereum/gateway/L1ArbitrumExtendedGateway.sol#L59-L76) to verify the source of the function definition.

### CODE REVIEW

**Comment by theoilie** [comment]
@cla-bot check

**Comment by theoilie** [comment]
@cla-bot check

**Comment by theoilie** [comment]
I signed the CLA, but the bot doesn't seem to recognize it. Is it just waiting to be counter-signed?

**Comment by theoilie** [comment]
@cla-bot check

**Comment by theoilie** [comment]
@hkalodner Would you be able to help out with this please? I've signed the CLA, but the verification is still failing.

**Comment by theoilie** [comment]
Giving this one a bump since it's been a couple weeks and it's a trivial change 🙂  @hkalodner @PlasmaPower @joshuacolvin0

**Comment by barathbitgo** [comment]
Can we please get this change in? I wasted significant amount of time due to the incorrect doc and wanted to make sure developers whoa re planning to develop on Arbitrum don't waste time in a similar manner 🙏

**Comment by theoilie** [comment]
> Can we please get this change in? I wasted significant amount of time due to the incorrect doc and wanted to make sure developers whoa re planning to develop on Arbitrum don't waste time in a similar manner 🙏

I'm having trouble getting anyone to review this PR. Please feel free to copy it and close this one, or ping any recently-active maintainers so they can give some insight into why the CLA bot is failing (I've signed it multiple times) and get this merged 😃  @hkalodner @PlasmaPower @joshuacolvin0

**Comment by theoilie** [comment]
@hkalodner @PlasmaPower @joshuacolvin0 looks like cla-bot is happy now! if we could get this merged I think it'll save devs like @barathbitgo some time 😃

**Comment by joshuacolvin0** [comment]
docs moved to Nitro repo

**Pull request closed without merging**
