### PR TITLE
Deduplicate Values when deserializing Machine type - Alternate implementation

### PR DESCRIPTION
**Pull request by joshuacolvin0**
This version populates Tuples as processing proceeds instead of collecting values in vector of vectors and populating each tuple all at once.

### CODE REVIEW

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           

Clones added
============
- packages/arb-avm-cpp/data_storage/src/value/value.cpp  2
         

Clones removed
==============
+ packages/arb-avm-cpp/tests/checkpoint.cpp  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6292982&bid=20472122)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           

Clones removed
==============
+ packages/arb-avm-cpp/tests/checkpoint.cpp  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6292982&bid=20472122)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           

Clones added
============
- packages/arb-avm-cpp/data_storage/src/value/value.cpp  4
         

Clones removed
==============
+ packages/arb-avm-cpp/tests/checkpoint.cpp  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6292982&bid=20472122)

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           

Clones added
============
- packages/arb-avm-cpp/tests/machine.cpp  2
- packages/arb-avm-cpp/data_storage/src/value/value.cpp  4
- packages/arb-avm-cpp/tests/datastack.cpp  2
         

Clones removed
==============
+ packages/arb-avm-cpp/tests/checkpoint.cpp  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6292982&bid=20472122)

**Comment by joshuacolvin0** [comment]
Cache values when reference_count > 1 or top level of requested value.

depth first, no caching
```
benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
restoreCheckpoint1                             100             1     1.19007 m
                                        697.188 ms    694.267 ms    701.598 ms
                                        17.9863 ms    13.3319 ms    28.3206 ms
User time (seconds): 75.94
Maximum resident set size (kbytes): 463264
```
depth first, cache only top level
```
benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
restoreCheckpoint1                             100           371     2.8196 ms
                                        68.5338 ns    68.3517 ns    68.8532 ns
                                        1.19333 ns    0.79246 ns    2.20604 ns
User time (seconds): 4.99
Maximum resident set size (kbytes): 459640
```

**Comment by hkalodner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
           

Clones added
============
- packages/arb-avm-cpp/tests/datastack.cpp  2
- packages/arb-avm-cpp/data_storage/src/value/value.cpp  4
         

Clones removed
==============
+ packages/arb-avm-cpp/tests/checkpoint.cpp  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OffchainLabs/arbitrum/pullRequest?prid=6292982&bid=20472122)

**Review by hkalodner — APPROVED** [review]
LGTM, this went through a bunch of review offline

**Pull request merged**
